// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwgxKKwFfxdHFiMepj7MHYvNMbk9c1AK8',
    appId: '1:604395501713:web:5ba9e2ad1923dcd3efa730',
    messagingSenderId: '604395501713',
    projectId: 'patronista-dae18',
    authDomain: 'patronista-dae18.firebaseapp.com',
    storageBucket: 'patronista-dae18.appspot.com',
    measurementId: 'G-J5J700K5PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3kXm9SnJ1xSBXMG-KVo00UydS4IGJ1Lc',
    appId: '1:604395501713:android:96faed6ac23906daefa730',
    messagingSenderId: '604395501713',
    projectId: 'patronista-dae18',
    storageBucket: 'patronista-dae18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Ne_7djko7N16OuFINJsI4orPtTkY0PU',
    appId: '1:604395501713:ios:6054bca8d8df8282efa730',
    messagingSenderId: '604395501713',
    projectId: 'patronista-dae18',
    storageBucket: 'patronista-dae18.appspot.com',
    iosClientId: '604395501713-j8djc7ipfjok70mq9lrpt2i966rub3j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.patronist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Ne_7djko7N16OuFINJsI4orPtTkY0PU',
    appId: '1:604395501713:ios:6054bca8d8df8282efa730',
    messagingSenderId: '604395501713',
    projectId: 'patronista-dae18',
    storageBucket: 'patronista-dae18.appspot.com',
    iosClientId: '604395501713-j8djc7ipfjok70mq9lrpt2i966rub3j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.patronist',
  );
}
