// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1aFIaPb3xuUSRcKIHIda7tvEyUHshyQ',
    appId: '1:438327085366:web:1238ca7cd9a79062780b97',
    messagingSenderId: '438327085366',
    projectId: 'the-patronista',
    authDomain: 'the-patronista.firebaseapp.com',
    storageBucket: 'the-patronista.appspot.com',
    measurementId: 'G-Q8W53B310Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-BFPjQ4E9f_zVz5iotb1rYPyVaL0c4eo',
    appId: '1:438327085366:android:9ef95e27e81662ad780b97',
    messagingSenderId: '438327085366',
    projectId: 'the-patronista',
    storageBucket: 'the-patronista.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7ncU97x13DGluA7PRQTUgQJ-7NN7Fy4',
    appId: '1:438327085366:ios:862e7da662571cca780b97',
    messagingSenderId: '438327085366',
    projectId: 'the-patronista',
    storageBucket: 'the-patronista.appspot.com',
    iosClientId: '438327085366-544lsp8e00ttkjv5tn4sfc4ok69v6d87.apps.googleusercontent.com',
    iosBundleId: 'com.example.patronist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ7ncU97x13DGluA7PRQTUgQJ-7NN7Fy4',
    appId: '1:438327085366:ios:862e7da662571cca780b97',
    messagingSenderId: '438327085366',
    projectId: 'the-patronista',
    storageBucket: 'the-patronista.appspot.com',
    iosClientId: '438327085366-544lsp8e00ttkjv5tn4sfc4ok69v6d87.apps.googleusercontent.com',
    iosBundleId: 'com.example.patronist',
  );
}
